module.exports = {
    'China': {
        'i': '🇨🇳',
        'g': ['Shanghai']
    },
    'India': {
        'i': '🇮🇳',
        'g': ['Gujarat', 'Ahmedabad', 'New Delhi', 'Mumbai', 'Lucknow', 'Northern Karnataka', 'Bangalore']
    },
    'South Africa': {
        'i': '🇿🇦',
        'g': ['Cape Town']
    },
    'USA': {
        'i': '🇺🇸',
        'g': ['US', 'Utah', 'Salt Lake City', 'New Mexico', 'Mt. View', 'California', 'Madison', 'Wisconsin', 'Chicago', 'San Francisco']
    },
    'UK': {
        'i': '🇬🇧',
        'g': ['Oxford', 'Newcastle-Upon-Tyne', 'Gateshead', 'Tyne and Wear', 'England', 'Nottingham']
    },
    'Argentina': {
        'i': '🇦🇷',
        'g': ['Buenos Aires']
    },
    'Germany': {
        'i': '🇩🇪',
        'g': ['Berlin', 'Göttingen', 'Frankfurt', 'Leipzig', 'Dresden', 'Hamburg']
    },
    'France': {
        'i': '🇫🇷',
        'g': ['Paris', 'République', 'Marseille', 'Bordeaux', 'Toulouse']
    },
    'Chile': {
        'i': '🇨🇱',
        'g': ['Santiago']
    },
    'Taiwan': {
        'i': '🇹🇼',
        'g': ['Taipei', 'Tainan']
    },
    'Turkey': {
        'i': '🇹🇷',
        'g': ['Istanbul']
    },
    'Wales': {
        'i': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
        'g': ['Borth', 'Ynyslas']
    },
    'Denmark': {
        'i': '🇩🇰',
        'g': ['Copenhagen']
    },
    'Mexico': {
        'i': '🇲🇽',
        'g': ['Ciudad de Mexico']
    },
    'software': {
        'i': '',
        'g': ['Postgres', 'Perl', 'code', 'text mining', 'optimization', 'programming', 'privacy', 'security', 'semantic web', 'URIs', 'REST', 'javascript', 'nodejs']
    },
    'Italy': {
        'i': '🇮🇹',
        'g': ['Fiesole', 'Roma', 'Ispra', 'Milano']
    },
    'Scotland': {
        'i': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
        'g': ['Edinburgh']
    },
    'cafés': {
        'i': '☕',
        'g': []
    },
    'restaurants': {
        'i': '🥘',
        'g': ['Coffee House']
    },
    'music': {
        'i': '🎼',
        'g': []
    },
    // 'bars': '🍸',
    // 'photos': '🖼️',
    // 'city': '🌆',
    // 'jazz': '🎷',
    // 'video': '📽️',
    // 'Committees': '',
    // 'CV': '',
    // 'presentation': '',
    // 'science': ':',
    // 'informal academies': '',
    // 'informal learning': '',
    // 'A Manifesto for Science': '',
    // 'Creative Commons': '',
    // 'romance': '',
    // 'OII': '',
    // 'Yiddish songs': '',
    // 'Smart Cities': '',
    // 'bio': '',
    // 'Genetic Data learning': '',
    // 'Workshops': '',
    // 'CODATA': '',
    // 'geospatial': '',
    // 'individual privacy': '',
    // 'web services': '',
    // 'presentation Workshops': '',
    // 'null': '',
    // 'Small is Beautiful': '',
    // 'CC0': '',
    // 'Publications': '',
    // 'graffiti': '',
    // 'murals': '',
    // 'web': '',
    // 'internet': '',
    // 'Vannevar Bush': '',
    // 'TDM': '',
    // 'project ideas': '',
    // 'open science': '',
    // 'publishing': '',
    // 'Memberships': '',
    // 'data chains': '',
    // 'album': '',
    // 'atlas': '',
    // 'Education': '',
    // 'Monk': '',
    // 'Thimmig': '',
    // 'licenses': '',
    // 'open source': '',
    // 'data sharing': '',
    // 'portraits': '',
    // 'The Residency': '',
    // 'health': '',
    // 'health data': '',
    // 'citizen-sourced information': '',
    // 'GIS': '',
    // 'rock': '',
    // 'wellness': '',
    // 'quality of life': '',
    // 'citizen science': '',
    // 'open data': '',
    // 'funding': '',
    // 'philanthropy': '',
    // 'recipe': '',
    // 'poetry': '',
    // 'prayer': '',
    // 'business models': '',
    // 'open licensing': '',
    // 'dogs': '',
    // 'life': '',
    // 'love': '',
    // 'kid': '',
    // 'Trinidad': '',
    // 'CC Science': '',
    // 'RWJF': '',
    // 'Sloan': '',
    // 'data': '',
    // 'Public Domain': '',
    // 'CC Licenses': '',
    // 'Tu et Moi': '',
    // 'sensors': '',
    // 'cellphones': '',
    // 'career': '',
    // 'job': '',
    // 'Mew Mew': '',
    // 'workshops': '',
    // 'Montreal Jazz Festival 2016': '',
    // 'cilantro': '',
    // 'tomatoes': '',
    // 'peanuts': '',
    // 'garlic': '',
    // 'onions': '',
    // 'lemon': '',
    // 'language': '',
    // 'Nada': '',
    // 'citizen engagement': '',
    // 'taxonomy': '',
    // 'governance': '',
    // 'hardware': '',
    // 'citizens consent': '',
    // 'big data': '',
    // 'coastal flooding': '',
    // 'animation': '',
    // 'Meetings': '',
    // 'DataCite': '',
    // 'citizen journalism': '',
    // 'copyright': '',
    // 'images': '',
    // 'Google': '',
    // 'hand drawn maps': '',
    // 'change': '',
    // 'contracts': '',
    // 'firms': '',
    // 'dumb cities': '',
    // 'traffic lights': '',
    // 'CUBE': '',
    // 'biohackspace': '',
    // 'webcam microscope': '',
    // 'cv': '',
    // 'poem': '',
    // 'industry-research partnership': '',
    // 'paying for free': '',
    // 'data apps': '',
    // 'raw data': '',
    // 'processed data': '',
    // 'information': '',
    // 'technology': '',
    // 'cc': '',
    // 'Digital Access': '',
    // 'digital library': '',
    // 'specimens': '',
    // 'geotagging': '',
    // 'The World Bank': '',
    // 'tech primer': '',
    // 'international development': '',
    // '3D Printing': '',
    // 'AI': '',
    // 'Blockchain': '',
    // 'Open Science': '',
    // 'Open Data': '',
    // 'Sensors': '',
    // 'markdown': '',
    // 'cc blog': '',
    // 'hate': '',
    // 'hanoz': '',
    // 'dad': '',
    // 'postgresql': '',
    // 'short story': '',
    // 'ethics': '',
    // 'integrity': '',
    // 'UPMC': '',
    // 'LOV': '',
    // 'CNRS': '',
    // 'Villefranch-sur-Mer': '',
    // 'Aufstrurz': '',
    // 'Jazzkeller 69': '',
    // 'mythology': '',
    // 'माया': '', 
    // 'commentary': '',
    // 'RDA': '',
    // 'legal interoperability': '',
    // 'Awards': '',
    // 'prose': '',
    // 'a-trane': '',
    // 'displaced': '',
    // 'refugee': '',
    // 'immigrant': '',
    // 'hope': '',
    // 'classical': '',
    // 'free': '',
    // 'open': '',
    // 'philosophy': '',
    // 'ownership': '',
    // 'public domain': '',
    // 'movie': '',
    // 'makerspace': '',
    // 'culture of health': '',
    // 'apps': '',
    // 'city planning': '',
    // 'public participation': '',
    // 'IoT': '',
    // 'Mongolia': '',
    // 'Mongolian Academy of Sciences': '',
    // 'MULS': '',
    // 'silence': '',
    // 'Anne Geddes': '',
    // 'Claire Geddes': '',
    // 'Kirkhill': '',
    // 'Karlstad': '',
    // 'Sweden': '',
    // 'geographic data, IP': '',
    // 'Elsinore': '',
    // 'Experience': '',
    // 'data repository': '',
    // 'greek yogurt': '',
    // 'molasses': '',
    // 'Urdu': '',
    // 'PostGIS': '',
    // 'PL/R': '',
    // 'kmeans': '',
    // 'R': '',
    // 'dying': '',
    // 'loving': '',
    // 'living': '',
    // 'connections': '',
    // 'Bhubaneshwar': '',
    // 'water quality': '',
    // 'Hong Kong': '',
    // 'art science': '',
    // 'environmental monitoring': '',
    // 'Martin Luther King, Jr.': '',
    // 'dream': '',
    // 'regret': '',
    // 'futility': '',
    // 'desire': '',
    // 'punk rock': '',
    // 'CC licenses': '',
    // 'NonCommercial': '',
    // 'irony': '',
    // 'TOS': '',
    // 'consent': '',
    // 'contract': '',
    // 'packaging': '',
    // 'reuse': '',
    // 'makerspaces': '',
    // 'aging': '',
    // 'knowledge transfer': '',
    // 'Dublin': '',
    // 'Ireland': '',
    // 'Josef Koudelka': '',
    // 'Helmut Newton': '',
    // 'C|O': '',
    // 'Museum für Fotografie': '',
    // 'idea': '',
    // 'patent': '',
    // 'Thomas Jefferson': '',
    // 'b-flat': '',
    // 'forestry': '',
    // 'JFM': '',
    // 'MAMBA': '',
    // 'firm': '',
    // 'entity shielding': '',
    // 'owner shielding': '',
    // 'JavaScript': '',
    // 'open hardware': '',
    // 'Arduino': '',
    // 'art': '',
    // 'Leipzig': '',
    // 'Goths': '',
    // 'East Germany': '',
    // 'libraries': '',
    // 'computing': '',
    // 'licensing': '',
    // 'scientific data': '',
    // 'CC': '',
    // 'Intellectual Property': '',
    // 'Copyright': '',
    // 'Pat Metheny': '',
    // 'location': '',
    // 'London': '',
    // 'cranes': '',
    // 'Los Angeles': '',
    // 'Istanbul Modern': '',
    // 'sqlite': '',
    // 'Plazi': '',
    // 'Maker Faire': '',
    // 'policy': '',
    // 'Nesara': '',
    // 'ma': '',
    // 'Imam Bara': '',
    // 'नेसरा': '', 
    // 'माँ': '', 
    // 'Pavan': '',
    // 'Usha': '',
    // 'bioprinter': '',
    // 'New Zealand': '',
    // 'open access': '',
    // 'OA': '',
    // 'St. Augustine': '',
    // 'Wien': '',
    // 'Austria': '',
    // 'open document': '',
    // 'OHL': '',
    // 'data certification': '',
    // 'FOSS': '',
    // 'CERN': '',
    // 'TAPR': '',
    // 'intellectual property': '',
    // 'medical data': '',
    // 'GDPR': '',
    // 'OKFN': '',
    // 'Helsinki': '',
    // 'Finland': '',
    // 'health services research': '',
    // 'business model': '',
    // 'Hannover': '',
    // 'nostalgia': '',
    // 'Sarajevo': '',
    // 'climate change': '',
    // 'PDL': '',
    // 'PhD': '',
    // 'Social Contracts': '',
    // 'Pablo Neruda': '',
    // 'conservation': '',
    // 'potimarron': '',
    // 'Hokkaido kürbis': '',
    // 'red kuri squash': '',
    // 'text and data mining': '',
    // 'badges': '',
    // 'APIs': '',
    // 'obituary': '',
    // 'HBCSE': '',
    // 'spectrophotometer': '',
    // 'rural development': '',
    // 'web design': '',
    // 'Washington DC': '',
    // 'IIM': '',
    // 'Dordogne': '',
    // 'Roger Bacon': '',
    // 'Earth Base': '',
    // 'air quality monitoring': '',
    // 'social contract': '',
    // 'open licenses': '',
    // 'situated learning': '',
    // 'creative commons': '',
    // 'opt-in': '',
    // 'opt-out': '',
    // 'Memex': '',
    // 'social networking': '',
    // 'sotto': '',
    // 'dancing': '',
    // 'UCGIS': '',
    // 'NCGIA': '',
    // 'MCA': '',
    // 'Genève': '',
    // 'Lugano': '',
    // 'Canal Saint-Martin': '',
    // 'tribute': '',
    // 'Walter Benjamin': '',
    // 'Laurie Anderson': '',
    // 'Paul Klée': '',
    // 'Atibaia': '',
    // 'Brazil': '',
    // 'streaming databases': '',
    // 'Cork': '',
    // 'friendship': '',
    // 'closed access': '',
    // 'limited access': '',
    // 'Text-mining': '',
    // 'stupidity': '',
    // 'design': '',
    // 'Ordnance Survey': '',
    // 'citizen sourced information': '',
    // 'to-do': '',
    // 'recursion': '',
    // 'projects': '',
    // 'refugees': '',
    // 'Yi Fu Tuan': '',
    // 'geography': '',
    // 'traditional knowledge': '',
    // 'Colorado': '',
    // 'trust': '',
    // 'risk': '',
    // 'truth': '',
    // 'bias': '',
    // 'liberal': '',
    // 'conservative': '',
    // 'story': '',
    // 'photo': '',
    // 'under water': '',
    // 'noise': '',
    // 'marine life': '',
    // 'commitment': '',
    // 'strategy': '',
    // 'Bashkia Tirana': '',
    // 'hidden': '',
    // 'ideas': '',
    // 'PSI': '',
    // 'linkbait': '',
    // 'iPad': '',
    // 'VGI': '',
    // 'Voronoi': '',
    // 'Göteborg': '',
    // 'wearables': '',
    // 'red tide': '',
    // 'progamming': '',
    // 'API': '',
    // 'GSDI9': '',
    // 'Schumpeter': '',
    // 'licensing etiquette': '',
    // 'reuse etiquette': '',
    // 'names': '',
    // 'illusion': '',
    // 'spell': '',
    // 'fantasy': '',
    // 'travels': '',
    // 'earthbase': '',
    // 'plugin': '',
    // 'autofill': '',
    // 'kids': '',
    // 'community driven conservation': '',
    // 'CPR': '',
    // 'Commons': '',
    // 'cultural appopriation': '',
    // 'Andy Warhol': '',
    // 'OSTI': '',
    // 'SQLite': '',
    // 'FTS': '',
    // 'MALBA': '',
    // 'Emmett Williams': '',
    // 'Liliana Porter': '',
};